//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarifador.ServiceColeta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceColeta.WebService_Coleta_BilhetesSoap")]
    public interface WebService_Coleta_BilhetesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tarifar", ReplyAction="*")]
        void Tarifar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tarifar", ReplyAction="*")]
        System.Threading.Tasks.Task TarifarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_Coleta_BilhetesSoapChannel : Tarifador.ServiceColeta.WebService_Coleta_BilhetesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_Coleta_BilhetesSoapClient : System.ServiceModel.ClientBase<Tarifador.ServiceColeta.WebService_Coleta_BilhetesSoap>, Tarifador.ServiceColeta.WebService_Coleta_BilhetesSoap {
        
        public WebService_Coleta_BilhetesSoapClient() {
        }
        
        public WebService_Coleta_BilhetesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_Coleta_BilhetesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_Coleta_BilhetesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_Coleta_BilhetesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Tarifar() {
            base.Channel.Tarifar();
        }
        
        public System.Threading.Tasks.Task TarifarAsync() {
            return base.Channel.TarifarAsync();
        }
    }
}
