//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarifador
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdr
    {
        public int idcdr { get; set; }
        public System.DateTime calldate { get; set; }
        public string clid { get; set; }
        public string src { get; set; }
        public string dst { get; set; }
        public string dcontext { get; set; }
        public string channel { get; set; }
        public string dstchannel { get; set; }
        public string lastapp { get; set; }
        public string lastdata { get; set; }
        public int duration { get; set; }
        public int billsec { get; set; }
        public string disposition { get; set; }
        public int amaflags { get; set; }
        public string accountcode { get; set; }
        public string uniqueid { get; set; }
        public string userfield { get; set; }
        public string recordingfile { get; set; }
        public string cnum { get; set; }
        public string cnam { get; set; }
        public string outbound_cnum { get; set; }
        public string outbound_cnam { get; set; }
        public string dst_cnam { get; set; }
        public string did { get; set; }
        public string tarifado { get; set; }
    }
}
