//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarifador
{
    using System;
    using System.Collections.Generic;
    
    public partial class operadora
    {
        public operadora()
        {
            this.grupotroncoes = new HashSet<grupotronco>();
            this.troncoes = new HashSet<tronco>();
            this.planotarifacaos = new HashSet<planotarifacao>();
        }
    
        public int operadoraID { get; set; }
        public Nullable<int> codigo { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<grupotronco> grupotroncoes { get; set; }
        public virtual ICollection<tronco> troncoes { get; set; }
        public virtual ICollection<planotarifacao> planotarifacaos { get; set; }
    }
}
