//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarifador
{
    using System;
    using System.Collections.Generic;
    
    public partial class planotarifacao
    {
        public planotarifacao()
        {
            this.troncoes = new HashSet<tronco>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string tempoMinimoChamada { get; set; }
        public string tempoMinimoTarifacao { get; set; }
        public int operadoraID { get; set; }
        public string periodicidadeTarifa { get; set; }
        public Nullable<decimal> taxaConexao { get; set; }
        public Nullable<decimal> ligacao_0300 { get; set; }
        public Nullable<decimal> dddCelular { get; set; }
        public Nullable<decimal> dddFixo { get; set; }
        public Nullable<decimal> localCelular { get; set; }
        public Nullable<decimal> localFixo { get; set; }
    
        public virtual operadora operadora { get; set; }
        public virtual ICollection<tronco> troncoes { get; set; }
    }
}
